"""add state defaults to products

Revision ID: 54dce56c1036
Revises: e6d5dbb1c790
Create Date: 2021-01-03 12:15:14.135565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dce56c1036'
down_revision = 'e6d5dbb1c790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('state', sa.String(), server_default='available', nullable=True))
    op.drop_column('products', 'available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('products', 'state')
    # ### end Alembic commands ###
