"""add uuid to products and components

Revision ID: 6b88c50de079
Revises: 1ffc51a1128f
Create Date: 2020-12-22 15:37:09.463977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b88c50de079'
down_revision = '1ffc51a1128f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'components', ['uuid'])
    op.add_column('products_components', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'products_components', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_components', type_='unique')
    op.drop_column('products_components', 'uuid')
    op.drop_constraint(None, 'components', type_='unique')
    op.drop_column('components', 'uuid')
    # ### end Alembic commands ###
