"""remove supplier from orders

Revision ID: 6ce15461b519
Revises: e049354c81d8
Create Date: 2020-12-22 12:30:08.614024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce15461b519'
down_revision = 'e049354c81d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('supplier', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
