"""initial migration

Revision ID: 7fe984e079f6
Revises: bb1fce04b586
Create Date: 2020-11-21 17:22:16.477044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fe984e079f6'
down_revision = 'bb1fce04b586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TODO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TODO',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TODO_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='TODO_pkey')
    )
    # ### end Alembic commands ###
