"""remove quantity on order and add onto orderproduct

Revision ID: d57417eb04f3
Revises: 6b88c50de079
Create Date: 2020-12-22 15:38:47.963553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57417eb04f3'
down_revision = '6b88c50de079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity')
    op.add_column('orders_products', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_products', 'quantity')
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
