"""add available defaults to products

Revision ID: e6d5dbb1c790
Revises: a24f9b3315e6
Create Date: 2021-01-03 11:53:07.018106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d5dbb1c790'
down_revision = 'a24f9b3315e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available')
    # ### end Alembic commands ###
